"""Model monitoring, drift detection, data quality, and safeguards (Phases 40-41)."""
from src.monitoring.drift_detector import DriftDetector, ReferenceDistribution, DriftReport
from src.monitoring.drift_monitor import DriftMonitor, MonitoringStatus
from src.monitoring.schema_drift import (
    SchemaDriftReport,
    SchemaStatus,
    FeatureAvailability,
    check_schema,
    check_feature_availability,
)
from src.monitoring.prediction_drift import (
    PredictionDriftReport,
    check_prediction_drift,
)
from src.monitoring.alert_manager import AlertManager, Alert, AlertState, AlertSeverity
from src.monitoring.safeguards import PromotionSafeguard, SafeguardStatus, SafeguardResult
from src.monitoring.label_awareness import (
    LabelAvailability,
    OutcomeMonitoringReport,
    check_label_availability,
    check_outcome_drift,
)
from src.monitoring.baseline_governance import (
    BaselineMetadata,
    BaselineSource,
    BaselineStatus,
    validate_baseline_source,
    create_baseline,
)
from src.monitoring.feature_contract import (
    FeatureCategory,
    FeatureStatus,
    MissingPolicy,
    FeatureSpec,
    ML_FEATURE_CONTRACT,
    ML_FEATURE_VERSION,
    ML_FEATURE_ORDER,
    validate_feature,
    validate_feature_vector,
    check_feature_ordering,
    classify_decision_time_availability,
)
from src.monitoring.numerical_robustness import (
    RobustnessResult,
    safe_float,
    clamp_value,
    process_feature,
    process_feature_vector,
    has_rejections,
    get_quality_summary,
)
from src.monitoring.feature_freshness import (
    FreshnessStatus,
    FreshnessResult,
    FRESHNESS_REQUIREMENTS,
    check_feature_freshness,
    check_vector_freshness,
    get_stale_features,
)
from src.monitoring.temporal_safeguards import (
    TemporalCheckStatus,
    TemporalCheckResult,
    check_timestamp_safety,
    check_timestamp_ordering,
    check_rolling_feature_causality,
    check_feature_causality,
)
from src.monitoring.data_quality import (
    DataQualityStatus,
    DataQualityReport,
    assess_data_quality,
)
from src.monitoring.runtime_enforcement import (
    EnforcementVerdict,
    EnforcementResult,
    enforce_before_inference,
    get_feature_contract_version,
    get_expected_feature_count,
    get_expected_feature_names,
)
from src.monitoring.promotion_gate import (
    GateStatus,
    PromotionVerdict,
    GateResult,
    PromotionDecision,
    PromotionBlockedError,
    PromotionToken,
    evaluate_promotion,
    assert_promotion_allowed,
    evaluate_real_world_validation,
    evaluate_model_artifact_binding,
    evaluate_governance_gates,
    evaluate_security_gates,
)
from src.monitoring.release_manifest import (
    ReleaseManifest,
    create_release_manifest,
    artifact_set_hash,
)
from src.monitoring.runtime_attestation import (
    RuntimeState,
    RuntimeAttestation,
    verify_release_for_load,
    build_attestation,
    detect_runtime_drift,
    check_registry_runtime_consistency,
    attestation_audit_payload,
    RELEASE_MANIFEST_FILENAME,
)
from src.monitoring.release_lifecycle import (
    ReleaseState,
    ReleaseRecord,
    ReleaseRegistry,
    verify_release_lifecycle,
    create_revoked_manifest,
)
from src.monitoring.forensic_release_history import (
    ForensicReleaseHistory,
    IncidentRecord,
    IncidentCategory,
    IncidentState,
    ReleaseTransitionRecord,
    ForensicSnapshot,
    EvidenceGap,
)
from src.monitoring.dataset_evidence import (
    DatasetEvidenceRecord,
    SourceClassification,
    AdmissionState,
    EvidenceLevel,
    AdmissionReport,
    run_admission_gates,
    EvaluationProtocol,
    EvaluationRecordIntegrity,
    ThresholdPolicy,
    audit_current_datasets,
    KNOWN_CANDIDATES,
    check_target_leakage,
    check_future_information,
    check_duplicate_contamination,
    check_train_test_contamination,
    validate_temporal_order,
)
from src.monitoring.dataset_discovery import (
    CandidateDataset,
    CandidateStatus,
    ProvenanceLevel,
    LicenseClassification,
    SourceChainRecord,
    FraudLabelEvidence,
    IndependenceEvidence,
    AdmissionPackage,
    DatasetDiscoveryWorkflow,
    reevaluate_known_candidates,
    discover_external_candidates,
)
from src.monitoring.dataset_acquisition import (
    DatasetAcquisitionRecord,
    ArtifactIdentity,
    SourceEvidenceItem,
    SourceEvidenceBundle,
    ControlledEvaluationPackage,
    DatasetAcquisitionWorkflow,
    AcquisitionStatus,
    ChecksumState,
    EvidenceVerificationStatus,
    attach_acquisition_to_candidate,
)
from src.monitoring.dataset_certification import (
    CandidateEvidenceMatrix,
    CertificationRecord,
    CertificationVerdict,
    DatasetCertificationWorkflow,
    GateEvidenceRecord,
    EvidenceStatus,
    investigate_all_known_candidates,
)
from src.monitoring.external_evaluation import (
    ExternalEvaluationHarness,
    EvaluationRunRecord,
    EvaluationStatus,
    AdmissionBoundary,
    AdmissionCheck,
    PreEvaluationSnapshot,
    ExclusionPolicy,
    ExclusionRule,
    FrozenThresholdPolicy,
    EvaluationMetrics,
    create_test_fixture_dataset,
    create_fixture_certification,
    DEFAULT_EXCLUSION_POLICY,
)
from src.monitoring.real_world_dataset_execution import (
    RealWorldDatasetExecution,
    ExecutionState,
    ProvenanceEvidence,
    LabelEvidence,
    TemporalEvidence,
    IndependenceEvidence,
    FeatureMapping,
    LeakageCheckResult,
    EligibilityCertificate,
    ForensicEvent,
    GateResult,
    create_fixture_execution,
)
from src.monitoring.real_world_validation_execution import (
    RealWorldValidationExecution,
    ValidationState,
    SelectionCondition,
    ValidationSnapshot,
    FrozenPreprocessingRecord,
    EvaluationResult,
    ValidationForensicEvent,
    create_fixture_validation,    build_fixture_selection_args,
    build_real_world_selection_args,
)
from src.monitoring.dataset_evidence_ingestion import (
    DatasetEvidenceIngestion,
    EvidencePackage,
    EvidenceItem,
    EvidenceManifest,
    EvidenceDiff,
    EvidenceCategoryGate,
    EvidencePackageState,
    EvidenceStatus,
    SourceCaptureLevel,
    create_fixture_evidence_package,
)
from src.monitoring.observability import (
    SecurityEventType,
    SecuritySeverity,
    SecurityEvent,
    StructuredLogEntry,
    OperationalMetrics,
    ModelTelemetry,
    AlertCondition,
    DEFAULT_ALERT_CONDITIONS,
    HealthLevel,
    HealthReport,
    SecurityIncidentLedger,
    AlertEvaluator,
    ObservabilityStore,
    generate_correlation_id,
)
from src.monitoring.lifecycle import (
    LifecycleState,
    LifecycleManager,
    get_lifecycle,
    reset_lifecycle,
)
from src.monitoring.outcome_trust import (
    TrustClass,
    OutcomeTrustPolicyVersion,
    SourcePolicy,
    SOURCE_POLICIES,
    POLICY_VERSION,
    TrustDecision,
    OutcomeTrustError,
    evaluate_outcome_trust,
    OutcomeTrustRecord,
    OutcomeTrustGovernor,
)
from src.monitoring.dataset_admission import (
    AdmissionState,
    ExclusionReason,
    DatasetCandidate,
    OutcomeAdmission,
    AdmissionStats,
    AdmissionResult,
    DatasetAdmissionEngine,
    make_dataset_candidate,
    FeatureCompatibilityState,
    FeatureSchemaDescriptor,
    evaluate_feature_compatibility,
    KNOWN_EXTERNAL_SCHEMAS,
)
from src.monitoring.dataset_ingestion import (
    DatasetClassification,
    LabelProvenance,
    DatasetProvenance,
    IngestionResult,
    DatasetIngestionError,
    ingest_dataset,
    scan_data_directory,
    compute_file_hash,
    KNOWN_DATASETS,
)
from src.monitoring.external_dataset_evidence import (
    EligibilityStatus,
    ReadinessStatus,
    IndependenceStatus,
    ProvenanceStatus,
    ExternalDatasetEvidence,
    EligibilityAssessment,
    ReadinessAssessment,
    EvaluationManifest,
    assess_eligibility,
    assess_external_dataset_readiness,
    build_evaluation_manifest,
    build_evidence_from_ingestion,
)
from src.monitoring.model_contract_reconciliation import (
    ReconciliationStatus,
    reconcile_model_contract,
)


__all__ = [
    # Existing
    "DriftDetector",
    "ReferenceDistribution",
    "DriftReport",
    # Phase 40 orchestrator
    "DriftMonitor",
    "MonitoringStatus",
    # Schema drift
    "SchemaDriftReport",
    "SchemaStatus",
    "FeatureAvailability",
    "check_schema",
    "check_feature_availability",
    # Prediction drift
    "PredictionDriftReport",
    "check_prediction_drift",
    # Alerts
    "AlertManager",
    "Alert",
    "AlertState",
    "AlertSeverity",
    # Safeguards
    "PromotionSafeguard",
    "SafeguardStatus",
    "SafeguardResult",
    # Label awareness
    "LabelAvailability",
    "OutcomeMonitoringReport",
    "check_label_availability",
    "check_outcome_drift",
    # Baseline governance
    "BaselineMetadata",
    "BaselineSource",
    "BaselineStatus",
    "validate_baseline_source",
    "create_baseline",
    # Phase 41: feature contract
    "FeatureCategory",
    "FeatureStatus",
    "MissingPolicy",
    "FeatureSpec",
    "ML_FEATURE_CONTRACT",
    "ML_FEATURE_VERSION",
    "ML_FEATURE_ORDER",
    "validate_feature",
    "validate_feature_vector",
    "check_feature_ordering",
    "classify_decision_time_availability",
    # Phase 41: numerical robustness
    "RobustnessResult",
    "safe_float",
    "clamp_value",
    "process_feature",
    "process_feature_vector",
    "has_rejections",
    "get_quality_summary",
    # Phase 41: feature freshness
    "FreshnessStatus",
    "FreshnessResult",
    "FRESHNESS_REQUIREMENTS",
    "check_feature_freshness",
    "check_vector_freshness",
    "get_stale_features",
    # Phase 41: temporal safeguards
    "TemporalCheckStatus",
    "TemporalCheckResult",
    "check_timestamp_safety",
    "check_timestamp_ordering",
    "check_rolling_feature_causality",
    "check_feature_causality",
    # Phase 41: data quality gates
    "DataQualityStatus",
    "DataQualityReport",
    "assess_data_quality",
    # Phase 42: runtime enforcement
    "EnforcementVerdict",
    "EnforcementResult",
    "enforce_before_inference",
    "get_feature_contract_version",
    "get_expected_feature_count",
    "get_expected_feature_names",
    # Phase 46: promotion gate
    "GateStatus",
    "PromotionVerdict",
    "GateResult",
    "PromotionDecision",
    "PromotionBlockedError",
    "PromotionToken",
    "evaluate_promotion",
    "assert_promotion_allowed",
    "evaluate_real_world_validation",
    "evaluate_model_artifact_binding",
    "evaluate_governance_gates",
    "evaluate_security_gates",
    # Phase 48: release manifest
    "ReleaseManifest",
    "create_release_manifest",
    "artifact_set_hash",
    # Phase 49: runtime attestation
    "RuntimeState",
    "RuntimeAttestation",
    "verify_release_for_load",
    "build_attestation",
    "detect_runtime_drift",
    "check_registry_runtime_consistency",
    "attestation_audit_payload",
    "RELEASE_MANIFEST_FILENAME",
    # Phase 51: release lifecycle
    "ReleaseState",
    "ReleaseRecord",
    "ReleaseRegistry",
    "verify_release_lifecycle",
    # Phase 52: forensic release history
    "ForensicReleaseHistory",
    "IncidentRecord",
    "IncidentCategory",
    "IncidentState",
    "ReleaseTransitionRecord",
    "ForensicSnapshot",
    "EvidenceGap",
    # Phase 53: dataset evidence & admission
    "DatasetEvidenceRecord",
    "SourceClassification",
    "AdmissionState",
    "EvidenceLevel",
    "AdmissionReport",
    "run_admission_gates",
    "EvaluationProtocol",
    "EvaluationRecordIntegrity",
    "ThresholdPolicy",
    "audit_current_datasets",
    "KNOWN_CANDIDATES",
    "check_target_leakage",
    "check_future_information",
    "check_duplicate_contamination",
    "check_train_test_contamination",
    "validate_temporal_order",
    # Phase 54: dataset discovery & provenance
    "CandidateDataset",
    "CandidateStatus",
    "ProvenanceLevel",
    "LicenseClassification",
    "SourceChainRecord",
    "FraudLabelEvidence",
    "IndependenceEvidence",
    "AdmissionPackage",
    "DatasetDiscoveryWorkflow",
    "reevaluate_known_candidates",
    "discover_external_candidates",
    # Phase 55: dataset acquisition & controlled evaluation
    "DatasetAcquisitionRecord",
    "ArtifactIdentity",
    "SourceEvidenceItem",
    "SourceEvidenceBundle",
    "ControlledEvaluationPackage",
    "DatasetAcquisitionWorkflow",
    "AcquisitionStatus",
    "ChecksumState",
    "EvidenceVerificationStatus",
    "attach_acquisition_to_candidate",
    # Phase 56: dataset certification
    "CandidateEvidenceMatrix",
    "CertificationRecord",
    "CertificationVerdict",
    "DatasetCertificationWorkflow",
    "GateEvidenceRecord",
    "EvidenceStatus",
    "investigate_all_known_candidates",
    # Phase 57: external evaluation harness
    "ExternalEvaluationHarness",
    "EvaluationRunRecord",
    "EvaluationStatus",
    "AdmissionBoundary",
    "AdmissionCheck",
    "PreEvaluationSnapshot",
    "ExclusionPolicy",
    "ExclusionRule",
    "FrozenThresholdPolicy",
    "EvaluationMetrics",
    "create_test_fixture_dataset",
    "create_fixture_certification",
    "DEFAULT_EXCLUSION_POLICY",
    # Phase 58: real-world dataset execution
    "RealWorldDatasetExecution",
    "ExecutionState",
    "ProvenanceEvidence",
    "LabelEvidence",
    "TemporalEvidence",
    "IndependenceEvidence",
    "FeatureMapping",
    "LeakageCheckResult",
    "EligibilityCertificate",
    "ForensicEvent",
    "GateResult",
    "create_fixture_execution",
    # Phase 59: real-world validation execution
    "RealWorldValidationExecution",
    "ValidationState",
    "SelectionCondition",
    "ValidationSnapshot",
    "FrozenPreprocessingRecord",
    "EvaluationResult",
    "ValidationForensicEvent",
    "create_fixture_validation",
    "build_fixture_selection_args",
    "build_real_world_selection_args",
    # Phase 60: dataset evidence ingestion
    "DatasetEvidenceIngestion",
    "EvidencePackage",
    "EvidenceItem",
    "EvidenceManifest",
    "EvidenceDiff",
    "EvidenceCategoryGate",
    "EvidencePackageState",
    "EvidenceStatus",
    "SourceCaptureLevel",
    "create_fixture_evidence_package",
    # Phase 70: observability
    "SecurityEventType",
    "SecuritySeverity",
    "SecurityEvent",
    "StructuredLogEntry",
    "OperationalMetrics",
    "ModelTelemetry",
    "AlertCondition",
    "DEFAULT_ALERT_CONDITIONS",
    "HealthLevel",
    "HealthReport",
    "SecurityIncidentLedger",
    "AlertEvaluator",
    "ObservabilityStore",
    "generate_correlation_id",
    # Phase 76: lifecycle
    "LifecycleState",
    "LifecycleManager",
    "get_lifecycle",
    "reset_lifecycle",
    # Phase 80: outcome pipeline
    "OutcomeLabel",
    "OutcomeStatus",
    "OutcomeSource",
    "OutcomeRecord",
    "OutcomeValidationError",
    "validate_outcome",
    "compute_outcome_hash",
    # Phase 81: outcome trust governance
    "TrustClass",
    "OutcomeTrustPolicyVersion",
    "SourcePolicy",
    "SOURCE_POLICIES",
    "POLICY_VERSION",
    "TrustDecision",
    "OutcomeTrustError",
    "evaluate_outcome_trust",
    "OutcomeTrustRecord",
    "OutcomeTrustGovernor",
    # Phase 82: dataset admission
    "AdmissionState",
    "ExclusionReason",
    "DatasetCandidate",
    "OutcomeAdmission",
    "AdmissionStats",
    "AdmissionResult",
    "DatasetAdmissionEngine",
    "make_dataset_candidate",
    "FeatureCompatibilityState",
    "FeatureSchemaDescriptor",
    "evaluate_feature_compatibility",
    "KNOWN_EXTERNAL_SCHEMAS",
    # Phase 84: dataset ingestion
    "DatasetClassification",
    "LabelProvenance",
    "DatasetProvenance",
    "IngestionResult",
    "DatasetIngestionError",
    "ingest_dataset",
    "scan_data_directory",
    "compute_file_hash",
    "KNOWN_DATASETS",
    # Phase 85: external dataset evidence
    "EligibilityStatus",
    "ReadinessStatus",
    "IndependenceStatus",
    "ProvenanceStatus",
    "ExternalDatasetEvidence",
    "EligibilityAssessment",
    "ReadinessAssessment",
    "EvaluationManifest",
    "assess_eligibility",
    "assess_external_dataset_readiness",
    "build_evaluation_manifest",
    "build_evidence_from_ingestion",
    # Phase 86: model contract reconciliation
    "ReconciliationStatus",
    "reconcile_model_contract",
    # Phase 88: IEEE-CIS forensic audit
    # Phase 89: institutional dataset registry
    # Phase 90: worldline access specification
    # Phase 91: worldline provider request & acceptance package validator
    # Phase 92: external dataset dry-run
    # Phase 93: real-world evaluation protocol
    # Phase 94: RWV readiness audit & evidence pack
    # Phase 95: provider evidence & dataset qualification gate
    # Phase 96: controlled RWV execution harness
    # Phase 97: RWV result adjudication & acceptance gate
    # Phase 98: RWV-to-promotion boundary & evidence integration
    # Phase 99: RWV evidence ledger & reproducibility certification
    # Phase 100: independent system-wide security & RWV audit
    # Phase 101: audit finding remediation & regression closure
    "adjudicate_rwv_result",
    "verify_adjudication_hash",
    "RWVAdjudication",
    "ValidityStatus",
    "AcceptanceStatus",
    "PromotionEvidenceStatus",
    "ValidityReason",
    "ADJUDICATION_POLICY_VERSION",
    "create_session",
    "run_synthetic_harness_test",
    "capture_model_identity",
    "build_evaluation_config",
    "compute_metrics",
    "validate_temporal_ordering",
    "validate_labels",
    "validate_feature_transformation",
    "compute_result_hash",
    "create_audit_event",
    "RWVSession",
    "EvaluationConfig",
    "ModelIdentitySnapshot",
    "DatasetIdentitySnapshot",
    "EvaluationMetrics",
    "RWVEvaluationRecord",
    "AuditEvent",
    "SessionState",
    "ExecutionStatus",
    "check_rwv_execution_eligibility",
    "qualify_dataset",
    "qualify_all_known_candidates",
    "compute_evidence_hash",
    "ProviderEvidence",
    "QualificationReport",
    "DatasetQualificationState",
    "EvidenceStatus",
    "QUALIFICATION_DIMENSIONS",
    "KNOWN_CANDIDATES",
    "run_readiness_audit",
    "build_evidence_pack",
    "validate_evidence_pack",
    "build_protocol",
    "build_identity_lock",
    "compute_metrics",
    "PRODUCTION_THRESHOLD",
    "run_dry_run",
    "run_all_scenarios",
    "ScenarioId",
    "build_provider_request",
    "validate_worldline_acceptance_package",
    "build_acceptance_package",
    "hash_acceptance_package",
    "generate_provider_checklist",
    "REQUIRED_SOURCE_FIELDS",
    "CANONICAL_48",
    "build_access_spec",
    "ACCEPTANCE_MATRIX",
    "WORLDLINE_ECOM_2017_NAG",
    "WORLDLINE_ONLINE_2018",
    "evaluate_access_package",
    "ingest_local_dataset",
    "run_registry",
    "get_preflight_summary",
    "CANONICAL_48",
    "WORLDLINE_RECORD",
    "NOVATTI_RECORD",
    "run_forensic_audit",
    "get_derivability_summary",
    "get_leakage_summary",
    "DERIVABILITY_MATRIX",
    "ENTITY_CONTINUITY",
    "IEEE_CIS_PROVENANCE",
    "LABEL_PROVENANCE",
]

# Phase 102: Production-Readiness Consistency & Evidence Reconciliation Audit

# Phase 103: Controlled Production-Readiness Closure Audit
